'6130':
  files:
    audio: null
    epub: /home/amar/projects/audino/data/6130/6130.epub
    raw: /home/amar/projects/audino/data/6130/6130.txt
    summary: /home/amar/projects/audino/data/6130/summary_20.txt
    thumbnail: /home/amar/projects/audino/data/6130/6130.jpg
  meta_data:
    AudioUrl: null
    Author: Homer
    Description: null
    Genre: poetry
    SummaryUrl: null
    ThumbnailUrl: null
    Title: The Iliad
'84':
  files:
    audio: /home/amar/projects/audino/data/84/audio_20.mp3
    epub: /home/amar/projects/audino/data/84/84.epub
    raw: /home/amar/projects/audino/data/84/84.txt
    summary: /home/amar/projects/audino/data/84/summary_20.txt
    thumbnail: /home/amar/projects/audino/data/84/84.jpg
  meta_data:
    AudioUrl: null
    Author: Mary Wollstonecraft Shelley
    Description: null
    Genre: fiction
    SummaryUrl: null
    ThumbnailUrl: null
    Title: Frankenstein; Or, The Modern Prometheus
