'6130':
  files:
    epub: /home/amar/projects/audino/data/6130/6130.epub
    genre: poetry
    raw: /home/amar/projects/audino/data/6130/6130.txt
    thumbnail: /home/amar/projects/audino/data/6130/6130.jpg
  meta_data:
    AudioUrl: null
    Author: null
    Description: null
    Genre: null
    SummaryUrl: null
    ThumbnailUrl: null
    Title: null
'84':
  files:
    epub: /home/amar/projects/audino/data/84/84.epub
    genre: fiction
    raw: /home/amar/projects/audino/data/84/84.txt
    thumbnail: /home/amar/projects/audino/data/84/84.jpg
  meta_data:
    AudioUrl: null
    Author: null
    Description: null
    Genre: null
    SummaryUrl: null
    ThumbnailUrl: null
    Title: null
