'6130':
  files:
    audio: null
    epub: /home/amar/projects/audino/data/6130/6130.epub
    html: /home/amar/projects/audino/data/6130/6130.html
    raw: /home/amar/projects/audino/data/6130/6130.txt
    summary_json: null
    summary_text: null
    thumbnail: /home/amar/projects/audino/data/6130/6130.jpg
  meta:
    AudioUrl: null
    Author: null
    Description: null
    Genre: Poetry
    SummaryUrl: null
    ThumbnailUrl: null
    Title: null
'84':
  files:
    audio: /home/amar/projects/audino/data/84/audio_20.mp3
    epub: /home/amar/projects/audino/data/84/84.epub
    raw: /home/amar/projects/audino/data/84/84.txt
    summary: /home/amar/projects/audino/data/84/summary_20.json
    thumbnail: /home/amar/projects/audino/data/84/84.jpg
  meta_data:
    AudioUrl: https://firebasestorage.googleapis.com/v0/b/audino-327610.appspot.com/o/84%2Faudio_20.mp3?alt=media
    Author: Mary Wollstonecraft Shelley
    Description: null
    Genre: fiction
    SummaryUrl: https://firebasestorage.googleapis.com/v0/b/audino-327610.appspot.com/o/84%2Fsummary_20.json?alt=media
    ThumbnailUrl: https://firebasestorage.googleapis.com/v0/b/audino-327610.appspot.com/o/84%2F84.jpg?alt=media
    Title: Frankenstein; Or, The Modern Prometheus
